apiVersion: v1
kind: Service
metadata:
  name: my-cluster-service
  namespace: default
spec:
  selector:
    app: myapp
    type: backend
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001